baseURL = 'https://restless-town.makyo.ink/'
languageCode = 'en-us'
title = 'Restless Town'
theme = 'maddybook'
paginatePath = ''

[permalinks]
    post = '/:filename/'

[params]
    author = 'Madison Scott-Clary'
    home = 'https://makyo.ink'
    copyright = 2019
    customCSS = ['/css/rt.css']

[markup.goldmark.renderer]
    unsafe = true
